### ISSUE TITLE
TensorFlow 2 PyTorch?

### ISSUE THREAD

**Issue by innat** [AlexanderLutsenko/nobuco#12]

**Comment by AlexanderLutsenko** [comment]
@innat But why?

**Comment by innat** [comment]
A few months ago, there was a Kaggle competition where a TF model was needed to submit. And [nobuco](https://www.kaggle.com/competitions/asl-signs/discussion/402545) did well.  Now, a new competition will be organized where the PyTorch model will be needed to submit.

**Comment by AlexanderLutsenko** [comment]
@innat I actually have the reverse converter written, although It's not nearly as sophisticated as Nobuco. Problem is, I don't think it's worth the effort. Hardly anyone uses Tensorflow as a research framework nowadays. What I believe has much potential is JAX. Perhaps we should focus on developing a JAX->Pytorch converter instead.

**Comment by innat** [comment]
> Hardly anyone uses Tensorflow as a research framework nowadays. 

We are considering general tools, not particular ones for the research area. And IMO, TensorFlow wouldn't be gone any time soon. 

> What I believe has much potential is JAX. Perhaps we should focus on developing a JAX->Pytorch converter instead.

Good stuff. 
This may interest you, https://twitter.com/fchollet/status/1678777783848419330

**Comment by AlexanderLutsenko** [comment]
> This may interest you, https://twitter.com/fchollet/status/1678777783848419330

@innat Wow, that's huge! Never seriously considered making a unified API since no one would trust my determination to support it for a number of years. But the Keras team may actually pull it off. Hope they don't change too many things in the upcoming release so I could add Keras 3 in Nobuco with a handful of import replacements.

**Comment by innat** [comment]
@AlexanderLutsenko 
Most probably, you can collaborate with keras-core and add functionalities of [nobuco](https://github.com/AlexanderLutsenko/nobuco) directly to keras-core as part of its APIs.

check: https://twitter.com/kornia_foss/status/1678837500083568643
check: https://github.com/keras-team/keras-core/issues/450

**Comment by AlexanderLutsenko** [comment]
@innat Thanks, I'll look into it.

**Comment by johndpope** [comment]
**background**
I arrived at this library due to a failed upgrade / side grade from pytorch to tensorflow (missing ops -  onnx / too slow - broken + hwhc headaces) 
i need the model in tensorflowjs to do some advanced webpgu stuff (like this https://github.com/shiguredo/media-processors) that doesn't seem possible with onnx.  with the twitter link above - does this mean keras 3  - we can port pytorch nn.module over to keras - and then potentially get to tensorflow js (bypassing nobuco)?  

i maybe overlooking something - but 
if i use this library to take a pytorch2 file  do the model conversion to keras - (already did this) - it spits out a keras file - 
if i save to h5 or keras does it make a difference?
I attempt to load it - to save to tensorflowjs


is there a supported version of tensorflowjs (take keras - spit out bin file) to go to tensorflowjs?

`
tensorflowjs_converter --input_format=keras implicit_motion_alignment.keras test
2024-10-18 15:46:56.398170: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2024-10-18 15:46:56.406687: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-10-18 15:46:56.416802: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-10-18 15:46:56.419778: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-10-18 15:46:56.426812: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2024-10-18 15:46:57.037827: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Traceback (most recent call last):
  File "/home/oem/miniconda3/envs/comfyui/bin/tensorflowjs_converter", line 8, in <module>
    sys.exit(pip_main())
             ^^^^^^^^^^
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/tensorflowjs/converters/converter.py", line 959, in pip_main
    main([' '.join(sys.argv[1:])])
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/tensorflowjs/converters/converter.py", line 963, in main
    convert(argv[0].split(' '))
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/tensorflowjs/converters/converter.py", line 949, in convert
    _dispatch_converter(input_format, output_format, args, quantization_dtype_map,
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/tensorflowjs/converters/converter.py", line 619, in _dispatch_converter
    dispatch_keras_h5_to_tfjs_layers_model_conversion(
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/tensorflowjs/converters/converter.py", line 84, in dispatch_keras_h5_to_tfjs_layers_model_conversion
    h5_file = h5py.File(h5_path, 'r')
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/h5py/_hl/files.py", line 561, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/oem/miniconda3/envs/comfyui/lib/python3.11/site-packages/h5py/_hl/files.py", line 235, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 102, in h5py.h5f.open
OSError: Unable to synchronously open file (file signature not found)

`


it seems like this library can only work with tensorflow 1....?
because 

    tensorflowjs 4.5 - depends on latest tensorflow 2 - does it mean keras 3 format ? is that the cause of signature error?  or its just a malformed keras saved file? but the prediction works - 


The conflict is caused by:
    tensorflow 2.12.0 depends on protobuf!=4.21.0, !=4.21.1, !=4.21.2, !=4.21.3, !=4.21.4, !=4.21.5, <5.0.0dev and >=3.20.3
    tensorflowjs 3.21.0 depends on protobuf<3.20 and >=3.9.2

can anyone confirm if they can get a saved keras file ported to tensorflowjs 
tensorflowjs_converter --input_format=keras YOURFILEHERE.keras test
