### ISSUE TITLE
ModuleNotFoundError: No module named 'keras.src.engine'

### ISSUE THREAD

**Issue by ivanstepanovftw** [AlexanderLutsenko/nobuco#27]
```
Traceback (most recent call last):
  File "/p/i/vline_haptic_joystick/waternet_tf.py", line 5, in <module>
    import nobuco
  File "/p/i/vline_haptic_joystick/.venv/lib/python3.12/site-packages/nobuco/__init__.py", line 1, in <module>
    from nobuco.converters.channel_ordering import t_pytorch2keras, t_keras2pytorch
  File "/p/i/vline_haptic_joystick/.venv/lib/python3.12/site-packages/nobuco/converters/channel_ordering.py", line 6, in <module>
    from nobuco.commons import ChannelOrder, TF_TENSOR_CLASSES
  File "/p/i/vline_haptic_joystick/.venv/lib/python3.12/site-packages/nobuco/commons.py", line 3, in <module>
    from keras.src.engine.keras_tensor import KerasTensor
ModuleNotFoundError: No module named 'keras.src.engine'
```
Both tensorflow and keras installed.

**Comment by AlexanderLutsenko** [comment]
Hi! Starting with `2.16-rc0`, Tensorflow resolves to Keras 3. The new Keras is not fully backward-compatible. Nobuco is tested with `2.15` and will continue to rely on the old Keras 2 until the first stable release of `2.16`.

**Comment by AlexanderLutsenko** [comment]
Transitioning to Keras 3 turned out more complicated than was advertised (see https://github.com/keras-team/keras/issues/19314). I'll get back to it as soon as there is more clarity regarding the new Keras' design.

**Comment by pedrofrodenas** [comment]
Yes, Indeed `keras.src.engine.keras_tensor` was moved to `from keras.src.backend import KerasTensor` . I already tried this but another errors arrise.

**Comment by AlexanderTekle** [comment]
do we still have to use tensorflow 2.15 to avoid this error?

**Comment by AlexanderLutsenko** [comment]
@AlexanderTekle Shortly put, yes.

**Comment by kabyanil** [comment]
Using tensorflow 2.15 works for model conversion, from pytorch to keras. But, I am not able to use tfjs_converted to convert the keras model to tfjs. I tried saving the keras model in both .keras and .h5 format, but it does not seem to work.

**Comment by johndpope** [comment]
folks at google should put some effort in to help here. i really want to use tfjs (bypassing onnx)- and yet getting my code over to tensorflow has been a complete ball breaker.
