### ISSUE TITLE
Conversion fails randomly on models with multiple inputs

### ISSUE THREAD

**Issue by mmjamm** [AlexanderLutsenko/nobuco#37]
Hi, Love the library!

I'm seeing random errors when trying to convert a PyTorch model with multiple inputs to Keras.
Is this a user error or a bug?

```
class ThreeInputModule(torch.nn.Module):

    def __init__(
            self,
            *args,
            **kwargs,
        ) -> None:
        super().__init__(*args, **kwargs)

        self.n1 = torch.nn.Linear(11, 4)
        self.n2 = torch.nn.Linear(12, 4)
        self.n3 = torch.nn.Linear(13, 4)

    def forward(
        self,
        x1: torch.Tensor,
        x2: torch.Tensor,
        x3: torch.Tensor
    ) -> tuple[torch.Tensor, torch.Tensor]:

        y1 = self.n1(x1)
        y2 = self.n2(x2)
        y3 = self.n3(x3)

        return y1 + y2 + y3

def main():
    model = ThreeInputModule()

    x1 = torch.rand((1, 2, 11))
    x2 = torch.rand((1, 2, 12))
    x3 = torch.rand((1, 2, 13))

    keras_module = nobuco.pytorch_to_keras(
        model=model,
        args=[x1, x2, x3],
    )

if __name__=="__main__":
     main()
```

The above code succeeds sometimes and fails other times. Failures seem to happen randomly. The error message suggests that when it fails, the input order is shuffled:
```
 D  File "nobuco-test/test_multiple_inputs.py", line 4 
ThreeInputModule[__main__](float32_0<1,2,11>, float32_1<1,2,12>, float32_0<1,2,13>) -> float32_9<1,2,4>
 │  Linear[torch.nn.modules.linear](float32_0<1,2,11>) -> float32_3<1,2,4>
 │   └· linear[torch.nn.functional](float32_0<1,2,11>, float32_2<4,11>, float32_2<4>) -> float32_3<1,2,4>
 │  Linear[torch.nn.modules.linear](float32_1<1,2,12>) -> float32_6<1,2,4>
 │   └· linear[torch.nn.functional](float32_1<1,2,12>, float32_4<4,12>, float32_5<4>) -> float32_6<1,2,4>
 │  Linear[torch.nn.modules.linear](float32_0<1,2,13>) -> float32_5<1,2,4>
 │   └· linear[torch.nn.functional](float32_0<1,2,13>, float32_7<4,13>, float32_4<4>) -> float32_5<1,2,4>
 │  __add__[torch.Tensor](float32_3<1,2,4>, float32_6<1,2,4>) -> float32_8<1,2,4>
 │   └· add[TensorBase](float32_3<1,2,4>, float32_6<1,2,4>) -> float32_8<1,2,4>
 ├· __add__[torch.Tensor](float32_8<1,2,4>, float32_5<1,2,4>) -> float32_9<1,2,4>
 └   └· add[TensorBase](float32_8<1,2,4>, float32_5<1,2,4>) -> float32_9<1,2,4>

Traceback (most recent call last):
  File "nobuco-test/test_multiple_inputs.py", line 42, in <module>
    main()
  File "nobuco-test/test_multiple_inputs.py", line 36, in main
    keras_module = nobuco.pytorch_to_keras(
  File ".virtualenvs/nobuco-test-cL41mlPZ/lib/site-packages/nobuco/convert.py", line 340, in pytorch_to_keras
    outputs_tf = keras_op(*args_tf, **kwargs_tf)
  File ".virtualenvs/nobuco-test-cL41mlPZ/lib/site-packages/nobuco/layers/container.py", line 69, in __call__
    outputs = op(*args, **kwargs)
  File ".virtualenvs/nobuco-test-cL41mlPZ/lib/site-packages/nobuco/layers/channel_order.py", line 59, in __call__
    outputs = self.func(*args, **kwargs)
  File ".virtualenvs/nobuco-test-cL41mlPZ/lib/site-packages/keras/src/utils/traceback_utils.py", line 70, in error_handler
    raise e.with_traceback(filtered_tb) from None
  File ".virtualenvs/nobuco-test-cL41mlPZ/lib/site-packages/tensorflow/python/framework/ops.py", line 1020, in _create_c_op
    raise ValueError(e.message)
ValueError: Exception encountered when calling layer "dense" (type Dense).

Dimensions must be equal, but are 13 and 11 for '{{node dense/Tensordot/MatMul}} = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false](dense/Tensordot/Reshape, dense/Tensordot/ReadVariableOp)' 
with input shapes: [2,13], [11,4].

Call arguments received by layer "dense" (type Dense):
  • inputs=tf.Tensor(shape=(1, 2, 13), dtype=float32)
```

Versions used:
* Python 3.11.1
* Tensorflow 2.15.0
* PyTorch 2.1.0
* Nobuco 0.13.3

**Comment by AlexanderLutsenko** [comment]
Hi! I just launched the script 50 times over, no issues found. Could that be a broken environment? A new Python (3.11)? Would you care to try it on a fresh env. with the following dependencies:

python 3.9
pip install torch torchvision torchaudio tensorflow==2.15 nobuco

**Comment by mmjamm** [comment]
Thank you for the fast response time!

I recreated the env on another machine using both your suggested dependencies and also what I had used originally and was not able to reproduce the issue either way.

I can still reproduce the problem on the original offending machine after recreating envs there, but it feels likely that it's a local problem. (The working configuration is on Linux and the problematic one is on Windows so it might also be a Windows problem, but my gut feeling is that it's some local problem in my environment.)

If there's something you'd like me to try, I can. 
I'm also ok to close this issue, since I wasn't able to reproduce it on Linux.

**Comment by AlexanderLutsenko** [comment]
Does a fresh environment work on Windows, though?

**Comment by mmjamm** [comment]
I couldn't get a fresh environment to work on Windows.

**Comment by AlexanderLutsenko** [comment]
Okay, I ran the script on a Windows machine, can confirm it's a bug. Thanks for reporting!

**Comment by AlexanderLutsenko** [comment]
I think I fixed the bug in `v0.14.0`. @mmjamm Let me know if it works for you!

**Comment by mmjamm** [comment]
> I think I fixed the bug in `v0.14.0`. @mmjamm Let me know if it works for you!

It works for me. Tested with `v0.14.4`.
Thank you very much!
